# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main_provider:
            entity:
                class:    UserBundle\Entity\User
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: plaintext
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # dev:
        #     pattern: ^/(_(profiler|wdt)|css|images|js|login)/
        #     security: false
        main_login:
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu   
        main_firewall:
            pattern:   ^/
            anonymous: true
            provider:  main_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
    # access_control:
    # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
