<?php

namespace MainBundle\Repository\Model;

/**
 * _TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _TestRepository extends \Doctrine\ORM\EntityRepository
{
}
