<?php

namespace MainBundle\Repository\Model;

/**
 * CategorieCourrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCourrierRepository extends \Doctrine\ORM\EntityRepository
{
}
