<?php

namespace MainBundle\Repository\Model;

/**
 * CourrierAffecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourrierAffecteRepository extends \Doctrine\ORM\EntityRepository
{
}
