<?php

namespace MainBundle\Repository\Model;

/**
 * CourrierRecuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourrierRecuRepository extends \Doctrine\ORM\EntityRepository
{
}
