<?php

namespace MainBundle\Repository\Model;

/**
 * CourrierArriveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourrierArriveeRepository extends \Doctrine\ORM\EntityRepository
{
}
