<?php

namespace MainBundle\Repository\Model;

/**
 * SousUniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousUniteRepository extends \Doctrine\ORM\EntityRepository
{
}
