services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
 UserBundle\DataFixtures\ORM\:
        resource: '../../DataFixtures/ORM'
        tags: ['doctrine.fixture.orm']
